-- liquibase formatted sql

---- changeset tokovenko:1
--CREATE TABLE client (
--id BIGINT PRIMARY KEY,
--fio TEXT,
--address TEXT,
--birthday DATE,
--passport TEXT,
--chat_id INTEGER,
--beginningDay DATE,
--pets INTEGER
--);
--
---- changeset tokovenko:2
--CREATE TABLE pet (
--id BIGINT PRIMARY KEY,
--name TEXT,
--birthday DATE,
--alive BOOLEAN,
--pet_variety VARCHAR,
--client_id BIGINT UNIQUE REFERENCES client(id)
--);
--
---- changeset tokovenko:3
--CREATE TABLE employee (
--id BIGINT PRIMARY KEY,
--fio TEXT,
--address TEXT,
--birthday DATE,
--passport TEXT,
--chat_id INTEGER,
--work_position TEXT
--);