-- liquibase formatted sql

-- changeset tokovenko:1
CREATE TABLE client (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	address varchar(255) NULL,
	birthday date NULL,
	chat_id BIGINT NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	passport varchar(255) NULL,
	user_name varchar(255) NULL,
	PRIMARY KEY (id)
);

-- changeset tokovenko:2
CREATE TABLE pet (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	alive bool NOT NULL,
	birthday date NULL,
	name varchar(255) NULL,
	pet_variety INTEGER NULL,
	client_id BIGINT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (client_id) REFERENCES client(id)
);

-- changeset tokovenko:3
CREATE TABLE employee (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	address varchar(255) NULL,
	birthday date NULL,
	chat_id BIGINT NULL,
	fio varchar(255) NULL,
	passport varchar(255) NULL,
	work_position varchar(255) NULL,
	PRIMARY KEY (id)
);

-- changeset tokovenko:4
CREATE TABLE info (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	key varchar(255) NULL,
	text varchar(255) NULL,
	PRIMARY KEY (id)
);

-- changeset tokovenko:5
CREATE TABLE avatar (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	data oid NULL,
	file_path varchar(255) NULL,
	file_size BIGINT NOT NULL,
	media_type varchar(255) NULL,
	pet_id BIGINT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (pet_id) REFERENCES pet(id)
);

-- changeset tokovenko:6
CREATE TABLE probation (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	client_id BIGINT NULL,
	last_date date NULL,
	pet_id BIGINT NULL,
	PRIMARY KEY (id)
);

-- changeset tokovenko:7
CREATE TABLE daily_report (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	brows bool NOT NULL,
	client_id BIGINT NULL,
	date date NULL,
	photo bytea NULL,
	text varchar(255) NULL,
	PRIMARY KEY (id)
);